backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "網站設定"
    files:
      - name: "announcements"
        label: "公告管理"
        file: "data/announcements.json"
        fields:
          - name: "announcements"
            label: "公告列表"
            widget: "list"
            fields:
              - {name: "text", label: "公告內容", widget: "string"}
              - {name: "priority", label: "優先級", widget: "select", options: ["high", "medium", "low"]}
              - {name: "active", label: "是否啟用", widget: "boolean", default: true}
              - {name: "startDate", label: "開始日期", widget: "datetime", required: false}
              - {name: "endDate", label: "結束日期", widget: "datetime", required: false}
      
      - name: "prices"
        label: "價格管理"
        file: "data/prices.json"
        fields:
          - name: "products"
            label: "產品價格"
            widget: "list"
            fields:
              - {name: "id", label: "產品ID", widget: "string"}
              - {name: "name", label: "產品名稱", widget: "string"}
              - {name: "price", label: "價格", widget: "number"}
              - {name: "originalPrice", label: "原價", widget: "number", required: false}
              - {name: "discount", label: "折扣", widget: "string", required: false}
              - {name: "lastUpdated", label: "更新時間", widget: "datetime", default: ""} 